data:
    image: busybox
    volumes:
        - ../:/var/www/sylius
        - /vendor
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        - ~/.composer:/root/.composer
        - /tmpfs

mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sylius_dev
        MYSQL_USER: sylius
        MYSQL_PASSWORD: sylius

php:
    build: php
    working_dir: /var/www/sylius
    volumes_from:
        - data
    links:
        - mysql
        - elasticsearch
        - memcached
    ports:
        - 8000:8000
    mem_limit: 2g
    command: bin/console server:start 0.0.0.0:8000

node:
    image: node:6
    working_dir: /var/www/sylius
    volumes_from:
        - data
    command: sh -c "npm install && npm run gulp"

elasticsearch:
    image: elasticsearch
    mem_limit: 512m
    memswap_limit: 1g

memcached:
    image: memcached
